/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Medagil API
 * Medagil 医学科研写作平台 API 规范（MVP 阶段）。 - 用户端与管理端 REST API，路径与 tag 区分 - 内部接口（internal tag）用于 api-service 与 ai-service / 其它服务间调用

 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthWeChatLoginRequest,
  AuthWeChatLoginResponse,
  CreateLibraryItemRequest,
  CreateProjectRequest,
  CreateTaskRequest,
  CreateTaskShareLink200,
  FileUploadResponse,
  GetLibraryItemsParams,
  GetPing200,
  GetProjectsParams,
  GetTasksParams,
  LibraryItem,
  LibraryListResponse,
  Plan,
  Project,
  ProjectListResponse,
  SearchParams,
  SearchResult,
  Subscription,
  TaskDetail,
  TaskFeedbackRequest,
  TaskListResponse,
  TaskMessage,
  UpdateProjectRequest,
  UpdateUserProfileRequest,
  UploadFileBody,
  UserProfile,
  WeChatJsapiOrderRequest,
  WeChatJsapiOrderResponse
} from './model';

import { useCustomInstance } from '../mutator/use-custom-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 用户端心跳
 */
export type getPingResponse200 = {
  data: GetPing200
  status: 200
}
    
export type getPingResponseSuccess = (getPingResponse200) & {
  headers: Headers;
};
;

export type getPingResponse = (getPingResponseSuccess)

export const getGetPingUrl = () => {


  

  return `/api/v1/ping`
}

export const getPing = async ( options?: RequestInit): Promise<getPingResponse> => {
  
  return useCustomInstance<getPingResponse>(getGetPingUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPingQueryKey = () => {
    return [
    `/api/v1/ping`
    ] as const;
    }

    
export const useGetPingQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPingQueryKey();

  const getPing =  useGetPingHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>> = ({ signal }) => getPing({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPingQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>>
export type GetPingQueryError = unknown


/**
 * @summary 用户端心跳
 */

export function useGetPing<TData = Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPingHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetPingQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 微信授权登录（Web/小程序）
 */
export type loginWithWeChatResponse200 = {
  data: AuthWeChatLoginResponse
  status: 200
}

export type loginWithWeChatResponse400 = {
  data: void
  status: 400
}

export type loginWithWeChatResponse401 = {
  data: void
  status: 401
}
    
export type loginWithWeChatResponseSuccess = (loginWithWeChatResponse200) & {
  headers: Headers;
};
export type loginWithWeChatResponseError = (loginWithWeChatResponse400 | loginWithWeChatResponse401) & {
  headers: Headers;
};

export type loginWithWeChatResponse = (loginWithWeChatResponseSuccess | loginWithWeChatResponseError)

export const getLoginWithWeChatUrl = () => {


  

  return `/api/v1/auth/wechat/login`
}

export const loginWithWeChat = async (authWeChatLoginRequest: AuthWeChatLoginRequest, options?: RequestInit): Promise<loginWithWeChatResponse> => {
  
  return useCustomInstance<loginWithWeChatResponse>(getLoginWithWeChatUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authWeChatLoginRequest,)
  }
);}




export const useLoginWithWeChatMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>, TError,{data: AuthWeChatLoginRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>, TError,{data: AuthWeChatLoginRequest}, TContext> => {

const mutationKey = ['loginWithWeChat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const loginWithWeChat =  useLoginWithWeChatHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>, {data: AuthWeChatLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginWithWeChat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithWeChatMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>>
    export type LoginWithWeChatMutationBody = AuthWeChatLoginRequest
    export type LoginWithWeChatMutationError = void

    /**
 * @summary 微信授权登录（Web/小程序）
 */
export const useLoginWithWeChat = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>, TError,{data: AuthWeChatLoginRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLoginWithWeChatHook>>>,
        TError,
        {data: AuthWeChatLoginRequest},
        TContext
      > => {

      const mutationOptions = useLoginWithWeChatMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 当前用户信息
 */
export type getMeResponse200 = {
  data: UserProfile
  status: 200
}

export type getMeResponse401 = {
  data: void
  status: 401
}
    
export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {


  

  return `/api/v1/me`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return useCustomInstance<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }

    
export const useGetMeQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  const getMe =  useGetMeHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>> = ({ signal }) => getMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>>
export type GetMeQueryError = void


/**
 * @summary 当前用户信息
 */

export function useGetMe<TData = Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 更新当前用户资料与偏好
 */
export type updateMeResponse200 = {
  data: UserProfile
  status: 200
}

export type updateMeResponse401 = {
  data: void
  status: 401
}
    
export type updateMeResponseSuccess = (updateMeResponse200) & {
  headers: Headers;
};
export type updateMeResponseError = (updateMeResponse401) & {
  headers: Headers;
};

export type updateMeResponse = (updateMeResponseSuccess | updateMeResponseError)

export const getUpdateMeUrl = () => {


  

  return `/api/v1/me`
}

export const updateMe = async (updateUserProfileRequest: UpdateUserProfileRequest, options?: RequestInit): Promise<updateMeResponse> => {
  
  return useCustomInstance<updateMeResponse>(getUpdateMeUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserProfileRequest,)
  }
);}




export const useUpdateMeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>, TError,{data: UpdateUserProfileRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>, TError,{data: UpdateUserProfileRequest}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const updateMe =  useUpdateMeHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>, {data: UpdateUserProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>>
    export type UpdateMeMutationBody = UpdateUserProfileRequest
    export type UpdateMeMutationError = void

    /**
 * @summary 更新当前用户资料与偏好
 */
export const useUpdateMe = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>, TError,{data: UpdateUserProfileRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdateMeHook>>>,
        TError,
        {data: UpdateUserProfileRequest},
        TContext
      > => {

      const mutationOptions = useUpdateMeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 项目列表
 */
export type getProjectsResponse200 = {
  data: ProjectListResponse
  status: 200
}
    
export type getProjectsResponseSuccess = (getProjectsResponse200) & {
  headers: Headers;
};
;

export type getProjectsResponse = (getProjectsResponseSuccess)

export const getGetProjectsUrl = (params?: GetProjectsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects?${stringifiedParams}` : `/api/v1/projects`
}

export const getProjects = async (params?: GetProjectsParams, options?: RequestInit): Promise<getProjectsResponse> => {
  
  return useCustomInstance<getProjectsResponse>(getGetProjectsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProjectsQueryKey = (params?: GetProjectsParams,) => {
    return [
    `/api/v1/projects`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetProjectsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>, TError = unknown>(params?: GetProjectsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsQueryKey(params);

  const getProjects =  useGetProjectsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>> = ({ signal }) => getProjects(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>>
export type GetProjectsQueryError = unknown


/**
 * @summary 项目列表
 */

export function useGetProjects<TData = Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>, TError = unknown>(
 params?: GetProjectsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 创建项目
 */
export type createProjectResponse201 = {
  data: Project
  status: 201
}

export type createProjectResponse400 = {
  data: void
  status: 400
}
    
export type createProjectResponseSuccess = (createProjectResponse201) & {
  headers: Headers;
};
export type createProjectResponseError = (createProjectResponse400) & {
  headers: Headers;
};

export type createProjectResponse = (createProjectResponseSuccess | createProjectResponseError)

export const getCreateProjectUrl = () => {


  

  return `/api/v1/projects`
}

export const createProject = async (createProjectRequest: CreateProjectRequest, options?: RequestInit): Promise<createProjectResponse> => {
  
  return useCustomInstance<createProjectResponse>(getCreateProjectUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectRequest,)
  }
);}




export const useCreateProjectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>, TError,{data: CreateProjectRequest}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createProject =  useCreateProjectHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>, {data: CreateProjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>>
    export type CreateProjectMutationBody = CreateProjectRequest
    export type CreateProjectMutationError = void

    /**
 * @summary 创建项目
 */
export const useCreateProject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateProjectHook>>>,
        TError,
        {data: CreateProjectRequest},
        TContext
      > => {

      const mutationOptions = useCreateProjectMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 项目详情
 */
export type getProjectByIdResponse200 = {
  data: Project
  status: 200
}

export type getProjectByIdResponse404 = {
  data: void
  status: 404
}
    
export type getProjectByIdResponseSuccess = (getProjectByIdResponse200) & {
  headers: Headers;
};
export type getProjectByIdResponseError = (getProjectByIdResponse404) & {
  headers: Headers;
};

export type getProjectByIdResponse = (getProjectByIdResponseSuccess | getProjectByIdResponseError)

export const getGetProjectByIdUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}`
}

export const getProjectById = async (projectId: string, options?: RequestInit): Promise<getProjectByIdResponse> => {
  
  return useCustomInstance<getProjectByIdResponse>(getGetProjectByIdUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProjectByIdQueryKey = (projectId?: string,) => {
    return [
    `/api/v1/projects/${projectId}`
    ] as const;
    }

    
export const useGetProjectByIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>, TError = void>(projectId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectByIdQueryKey(projectId);

  const getProjectById =  useGetProjectByIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>> = ({ signal }) => getProjectById(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProjectByIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>>
export type GetProjectByIdQueryError = void


/**
 * @summary 项目详情
 */

export function useGetProjectById<TData = Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>, TError = void>(
 projectId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProjectByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetProjectByIdQueryOptions(projectId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 更新项目
 */
export type updateProjectResponse200 = {
  data: Project
  status: 200
}
    
export type updateProjectResponseSuccess = (updateProjectResponse200) & {
  headers: Headers;
};
;

export type updateProjectResponse = (updateProjectResponseSuccess)

export const getUpdateProjectUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}`
}

export const updateProject = async (projectId: string,
    updateProjectRequest: UpdateProjectRequest, options?: RequestInit): Promise<updateProjectResponse> => {
  
  return useCustomInstance<updateProjectResponse>(getUpdateProjectUrl(projectId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectRequest,)
  }
);}




export const useUpdateProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const updateProject =  useUpdateProjectHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>, {projectId: string;data: UpdateProjectRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  updateProject(projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>>
    export type UpdateProjectMutationBody = UpdateProjectRequest
    export type UpdateProjectMutationError = unknown

    /**
 * @summary 更新项目
 */
export const useUpdateProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdateProjectHook>>>,
        TError,
        {projectId: string;data: UpdateProjectRequest},
        TContext
      > => {

      const mutationOptions = useUpdateProjectMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 删除或归档项目
 */
export type deleteProjectResponse204 = {
  data: void
  status: 204
}
    
export type deleteProjectResponseSuccess = (deleteProjectResponse204) & {
  headers: Headers;
};
;

export type deleteProjectResponse = (deleteProjectResponseSuccess)

export const getDeleteProjectUrl = (projectId: string,) => {


  

  return `/api/v1/projects/${projectId}`
}

export const deleteProject = async (projectId: string, options?: RequestInit): Promise<deleteProjectResponse> => {
  
  return useCustomInstance<deleteProjectResponse>(getDeleteProjectUrl(projectId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const useDeleteProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>, TError,{projectId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const deleteProject =  useDeleteProjectHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteProject(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>>
    
    export type DeleteProjectMutationError = unknown

    /**
 * @summary 删除或归档项目
 */
export const useDeleteProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>, TError,{projectId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteProjectHook>>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = useDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 成果库列表
 */
export type getLibraryItemsResponse200 = {
  data: LibraryListResponse
  status: 200
}
    
export type getLibraryItemsResponseSuccess = (getLibraryItemsResponse200) & {
  headers: Headers;
};
;

export type getLibraryItemsResponse = (getLibraryItemsResponseSuccess)

export const getGetLibraryItemsUrl = (params?: GetLibraryItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library?${stringifiedParams}` : `/api/v1/library`
}

export const getLibraryItems = async (params?: GetLibraryItemsParams, options?: RequestInit): Promise<getLibraryItemsResponse> => {
  
  return useCustomInstance<getLibraryItemsResponse>(getGetLibraryItemsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetLibraryItemsQueryKey = (params?: GetLibraryItemsParams,) => {
    return [
    `/api/v1/library`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetLibraryItemsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>, TError = unknown>(params?: GetLibraryItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLibraryItemsQueryKey(params);

  const getLibraryItems =  useGetLibraryItemsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>> = ({ signal }) => getLibraryItems(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLibraryItemsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>>
export type GetLibraryItemsQueryError = unknown


/**
 * @summary 成果库列表
 */

export function useGetLibraryItems<TData = Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>, TError = unknown>(
 params?: GetLibraryItemsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetLibraryItemsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetLibraryItemsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 将任务结果保存到成果库
 */
export type createLibraryItemResponse201 = {
  data: LibraryItem
  status: 201
}
    
export type createLibraryItemResponseSuccess = (createLibraryItemResponse201) & {
  headers: Headers;
};
;

export type createLibraryItemResponse = (createLibraryItemResponseSuccess)

export const getCreateLibraryItemUrl = () => {


  

  return `/api/v1/library`
}

export const createLibraryItem = async (createLibraryItemRequest: CreateLibraryItemRequest, options?: RequestInit): Promise<createLibraryItemResponse> => {
  
  return useCustomInstance<createLibraryItemResponse>(getCreateLibraryItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLibraryItemRequest,)
  }
);}




export const useCreateLibraryItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>, TError,{data: CreateLibraryItemRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>, TError,{data: CreateLibraryItemRequest}, TContext> => {

const mutationKey = ['createLibraryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createLibraryItem =  useCreateLibraryItemHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>, {data: CreateLibraryItemRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLibraryItem(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLibraryItemMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>>
    export type CreateLibraryItemMutationBody = CreateLibraryItemRequest
    export type CreateLibraryItemMutationError = unknown

    /**
 * @summary 将任务结果保存到成果库
 */
export const useCreateLibraryItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>, TError,{data: CreateLibraryItemRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateLibraryItemHook>>>,
        TError,
        {data: CreateLibraryItemRequest},
        TContext
      > => {

      const mutationOptions = useCreateLibraryItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 任务列表
 */
export type getTasksResponse200 = {
  data: TaskListResponse
  status: 200
}
    
export type getTasksResponseSuccess = (getTasksResponse200) & {
  headers: Headers;
};
;

export type getTasksResponse = (getTasksResponseSuccess)

export const getGetTasksUrl = (params?: GetTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/tasks?${stringifiedParams}` : `/api/v1/tasks`
}

export const getTasks = async (params?: GetTasksParams, options?: RequestInit): Promise<getTasksResponse> => {
  
  return useCustomInstance<getTasksResponse>(getGetTasksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTasksQueryKey = (params?: GetTasksParams,) => {
    return [
    `/api/v1/tasks`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetTasksQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>, TError = unknown>(params?: GetTasksParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksQueryKey(params);

  const getTasks =  useGetTasksHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>> = ({ signal }) => getTasks(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTasksQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>>
export type GetTasksQueryError = unknown


/**
 * @summary 任务列表
 */

export function useGetTasks<TData = Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>, TError = unknown>(
 params?: GetTasksParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTasksHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetTasksQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 新建任务
 */
export type createTaskResponse201 = {
  data: TaskDetail
  status: 201
}
    
export type createTaskResponseSuccess = (createTaskResponse201) & {
  headers: Headers;
};
;

export type createTaskResponse = (createTaskResponseSuccess)

export const getCreateTaskUrl = () => {


  

  return `/api/v1/tasks`
}

export const createTask = async (createTaskRequest: CreateTaskRequest, options?: RequestInit): Promise<createTaskResponse> => {
  
  return useCustomInstance<createTaskResponse>(getCreateTaskUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTaskRequest,)
  }
);}




export const useCreateTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>, TError,{data: CreateTaskRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>, TError,{data: CreateTaskRequest}, TContext> => {

const mutationKey = ['createTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createTask =  useCreateTaskHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>, {data: CreateTaskRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTask(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>>
    export type CreateTaskMutationBody = CreateTaskRequest
    export type CreateTaskMutationError = unknown

    /**
 * @summary 新建任务
 */
export const useCreateTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>, TError,{data: CreateTaskRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateTaskHook>>>,
        TError,
        {data: CreateTaskRequest},
        TContext
      > => {

      const mutationOptions = useCreateTaskMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 任务详情
 */
export type getTaskByIdResponse200 = {
  data: TaskDetail
  status: 200
}

export type getTaskByIdResponse404 = {
  data: void
  status: 404
}
    
export type getTaskByIdResponseSuccess = (getTaskByIdResponse200) & {
  headers: Headers;
};
export type getTaskByIdResponseError = (getTaskByIdResponse404) & {
  headers: Headers;
};

export type getTaskByIdResponse = (getTaskByIdResponseSuccess | getTaskByIdResponseError)

export const getGetTaskByIdUrl = (taskId: string,) => {


  

  return `/api/v1/tasks/${taskId}`
}

export const getTaskById = async (taskId: string, options?: RequestInit): Promise<getTaskByIdResponse> => {
  
  return useCustomInstance<getTaskByIdResponse>(getGetTaskByIdUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTaskByIdQueryKey = (taskId?: string,) => {
    return [
    `/api/v1/tasks/${taskId}`
    ] as const;
    }

    
export const useGetTaskByIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>, TError = void>(taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskByIdQueryKey(taskId);

  const getTaskById =  useGetTaskByIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>> = ({ signal }) => getTaskById(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTaskByIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>>
export type GetTaskByIdQueryError = void


/**
 * @summary 任务详情
 */

export function useGetTaskById<TData = Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>, TError = void>(
 taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetTaskByIdQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 任务消息与步骤
 */
export type getTaskMessagesResponse200 = {
  data: TaskMessage[]
  status: 200
}
    
export type getTaskMessagesResponseSuccess = (getTaskMessagesResponse200) & {
  headers: Headers;
};
;

export type getTaskMessagesResponse = (getTaskMessagesResponseSuccess)

export const getGetTaskMessagesUrl = (taskId: string,) => {


  

  return `/api/v1/tasks/${taskId}/messages`
}

export const getTaskMessages = async (taskId: string, options?: RequestInit): Promise<getTaskMessagesResponse> => {
  
  return useCustomInstance<getTaskMessagesResponse>(getGetTaskMessagesUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTaskMessagesQueryKey = (taskId?: string,) => {
    return [
    `/api/v1/tasks/${taskId}/messages`
    ] as const;
    }

    
export const useGetTaskMessagesQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>, TError = unknown>(taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskMessagesQueryKey(taskId);

  const getTaskMessages =  useGetTaskMessagesHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>> = ({ signal }) => getTaskMessages(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTaskMessagesQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>>
export type GetTaskMessagesQueryError = unknown


/**
 * @summary 任务消息与步骤
 */

export function useGetTaskMessages<TData = Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>, TError = unknown>(
 taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetTaskMessagesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetTaskMessagesQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 提交任务结果反馈
 */
export type submitTaskFeedbackResponse204 = {
  data: void
  status: 204
}
    
export type submitTaskFeedbackResponseSuccess = (submitTaskFeedbackResponse204) & {
  headers: Headers;
};
;

export type submitTaskFeedbackResponse = (submitTaskFeedbackResponseSuccess)

export const getSubmitTaskFeedbackUrl = (taskId: string,) => {


  

  return `/api/v1/tasks/${taskId}/feedback`
}

export const submitTaskFeedback = async (taskId: string,
    taskFeedbackRequest: TaskFeedbackRequest, options?: RequestInit): Promise<submitTaskFeedbackResponse> => {
  
  return useCustomInstance<submitTaskFeedbackResponse>(getSubmitTaskFeedbackUrl(taskId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      taskFeedbackRequest,)
  }
);}




export const useSubmitTaskFeedbackMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>, TError,{taskId: string;data: TaskFeedbackRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>, TError,{taskId: string;data: TaskFeedbackRequest}, TContext> => {

const mutationKey = ['submitTaskFeedback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const submitTaskFeedback =  useSubmitTaskFeedbackHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>, {taskId: string;data: TaskFeedbackRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  submitTaskFeedback(taskId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitTaskFeedbackMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>>
    export type SubmitTaskFeedbackMutationBody = TaskFeedbackRequest
    export type SubmitTaskFeedbackMutationError = unknown

    /**
 * @summary 提交任务结果反馈
 */
export const useSubmitTaskFeedback = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>, TError,{taskId: string;data: TaskFeedbackRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSubmitTaskFeedbackHook>>>,
        TError,
        {taskId: string;data: TaskFeedbackRequest},
        TContext
      > => {

      const mutationOptions = useSubmitTaskFeedbackMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 生成任务结果分享链接
 */
export type createTaskShareLinkResponse200 = {
  data: CreateTaskShareLink200
  status: 200
}
    
export type createTaskShareLinkResponseSuccess = (createTaskShareLinkResponse200) & {
  headers: Headers;
};
;

export type createTaskShareLinkResponse = (createTaskShareLinkResponseSuccess)

export const getCreateTaskShareLinkUrl = (taskId: string,) => {


  

  return `/api/v1/tasks/${taskId}/share`
}

export const createTaskShareLink = async (taskId: string, options?: RequestInit): Promise<createTaskShareLinkResponse> => {
  
  return useCustomInstance<createTaskShareLinkResponse>(getCreateTaskShareLinkUrl(taskId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const useCreateTaskShareLinkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>, TError,{taskId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>, TError,{taskId: string}, TContext> => {

const mutationKey = ['createTaskShareLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createTaskShareLink =  useCreateTaskShareLinkHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>, {taskId: string}> = (props) => {
          const {taskId} = props ?? {};

          return  createTaskShareLink(taskId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskShareLinkMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>>
    
    export type CreateTaskShareLinkMutationError = unknown

    /**
 * @summary 生成任务结果分享链接
 */
export const useCreateTaskShareLink = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>, TError,{taskId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateTaskShareLinkHook>>>,
        TError,
        {taskId: string},
        TContext
      > => {

      const mutationOptions = useCreateTaskShareLinkMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 上传文件（任务输入 / 成果库 / 知识库）
 */
export type uploadFileResponse201 = {
  data: FileUploadResponse
  status: 201
}
    
export type uploadFileResponseSuccess = (uploadFileResponse201) & {
  headers: Headers;
};
;

export type uploadFileResponse = (uploadFileResponseSuccess)

export const getUploadFileUrl = () => {


  

  return `/api/v1/files/upload`
}

export const uploadFile = async (uploadFileBody: UploadFileBody, options?: RequestInit): Promise<uploadFileResponse> => {
    const formData = new FormData();
if(uploadFileBody.file !== undefined) {
 formData.append(`file`, uploadFileBody.file)
 }
if(uploadFileBody.kind !== undefined) {
 formData.append(`kind`, uploadFileBody.kind)
 }

  return useCustomInstance<uploadFileResponse>(getUploadFileUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const useUploadFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>, TError,{data: UploadFileBody}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>, TError,{data: UploadFileBody}, TContext> => {

const mutationKey = ['uploadFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const uploadFile =  useUploadFileHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>, {data: UploadFileBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadFile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadFileMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>>
    export type UploadFileMutationBody = UploadFileBody
    export type UploadFileMutationError = unknown

    /**
 * @summary 上传文件（任务输入 / 成果库 / 知识库）
 */
export const useUploadFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>, TError,{data: UploadFileBody}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUploadFileHook>>>,
        TError,
        {data: UploadFileBody},
        TContext
      > => {

      const mutationOptions = useUploadFileMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 全局搜索（任务 / 项目 / 成果库）
 */
export type searchResponse200 = {
  data: SearchResult
  status: 200
}
    
export type searchResponseSuccess = (searchResponse200) & {
  headers: Headers;
};
;

export type searchResponse = (searchResponseSuccess)

export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search?${stringifiedParams}` : `/api/v1/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<searchResponse> => {
  
  return useCustomInstance<searchResponse>(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchQueryKey = (params?: SearchParams,) => {
    return [
    `/api/v1/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useSearchQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useSearchHook>>>, TError = unknown>(params: SearchParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchQueryKey(params);

  const search =  useSearchHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useSearchHook>>>> = ({ signal }) => search(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSearchHook>>>>
export type SearchQueryError = unknown


/**
 * @summary 全局搜索（任务 / 项目 / 成果库）
 */

export function useSearch<TData = Awaited<ReturnType<ReturnType<typeof useSearchHook>>>, TError = unknown>(
 params: SearchParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useSearchHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useSearchQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 订阅套餐列表
 */
export type getPlansResponse200 = {
  data: Plan[]
  status: 200
}
    
export type getPlansResponseSuccess = (getPlansResponse200) & {
  headers: Headers;
};
;

export type getPlansResponse = (getPlansResponseSuccess)

export const getGetPlansUrl = () => {


  

  return `/api/v1/plans`
}

export const getPlans = async ( options?: RequestInit): Promise<getPlansResponse> => {
  
  return useCustomInstance<getPlansResponse>(getGetPlansUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPlansQueryKey = () => {
    return [
    `/api/v1/plans`
    ] as const;
    }

    
export const useGetPlansQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlansQueryKey();

  const getPlans =  useGetPlansHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>> = ({ signal }) => getPlans({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlansQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>>
export type GetPlansQueryError = unknown


/**
 * @summary 订阅套餐列表
 */

export function useGetPlans<TData = Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPlansHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetPlansQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 当前用户订阅状态
 */
export type getSubscriptionResponse200 = {
  data: Subscription
  status: 200
}
    
export type getSubscriptionResponseSuccess = (getSubscriptionResponse200) & {
  headers: Headers;
};
;

export type getSubscriptionResponse = (getSubscriptionResponseSuccess)

export const getGetSubscriptionUrl = () => {


  

  return `/api/v1/subscription`
}

export const getSubscription = async ( options?: RequestInit): Promise<getSubscriptionResponse> => {
  
  return useCustomInstance<getSubscriptionResponse>(getGetSubscriptionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSubscriptionQueryKey = () => {
    return [
    `/api/v1/subscription`
    ] as const;
    }

    
export const useGetSubscriptionQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionQueryKey();

  const getSubscription =  useGetSubscriptionHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>> = ({ signal }) => getSubscription({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSubscriptionQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>>
export type GetSubscriptionQueryError = unknown


/**
 * @summary 当前用户订阅状态
 */

export function useGetSubscription<TData = Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSubscriptionHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetSubscriptionQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 创建微信 JSAPI/小程序支付订单
 */
export type createWeChatJsapiOrderResponse200 = {
  data: WeChatJsapiOrderResponse
  status: 200
}
    
export type createWeChatJsapiOrderResponseSuccess = (createWeChatJsapiOrderResponse200) & {
  headers: Headers;
};
;

export type createWeChatJsapiOrderResponse = (createWeChatJsapiOrderResponseSuccess)

export const getCreateWeChatJsapiOrderUrl = () => {


  

  return `/api/v1/pay/wechat/jsapi`
}

export const createWeChatJsapiOrder = async (weChatJsapiOrderRequest: WeChatJsapiOrderRequest, options?: RequestInit): Promise<createWeChatJsapiOrderResponse> => {
  
  return useCustomInstance<createWeChatJsapiOrderResponse>(getCreateWeChatJsapiOrderUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      weChatJsapiOrderRequest,)
  }
);}




export const useCreateWeChatJsapiOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>, TError,{data: WeChatJsapiOrderRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>, TError,{data: WeChatJsapiOrderRequest}, TContext> => {

const mutationKey = ['createWeChatJsapiOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createWeChatJsapiOrder =  useCreateWeChatJsapiOrderHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>, {data: WeChatJsapiOrderRequest}> = (props) => {
          const {data} = props ?? {};

          return  createWeChatJsapiOrder(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWeChatJsapiOrderMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>>
    export type CreateWeChatJsapiOrderMutationBody = WeChatJsapiOrderRequest
    export type CreateWeChatJsapiOrderMutationError = unknown

    /**
 * @summary 创建微信 JSAPI/小程序支付订单
 */
export const useCreateWeChatJsapiOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>, TError,{data: WeChatJsapiOrderRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateWeChatJsapiOrderHook>>>,
        TError,
        {data: WeChatJsapiOrderRequest},
        TContext
      > => {

      const mutationOptions = useCreateWeChatJsapiOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
