/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Medagil API
 * Medagil 医学科研写作平台 API 规范（MVP 阶段）。 - 用户端与管理端 REST API，路径与 tag 区分 - 内部接口（internal tag）用于 api-service 与 ai-service / 其它服务间调用

 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdjustCreditRequest,
  AdminOrder,
  AdminOrderListResponse,
  AdminUserDetail,
  AdminUserListResponse,
  AuditLogListResponse,
  CreditAccountListResponse,
  CreditTransactionListResponse,
  DashboardStats,
  GetAdminOrdersParams,
  GetAdminPing200,
  GetAdminTasksParams,
  GetAdminUsersParams,
  GetAuditLogsParams,
  GetCreditAccountsParams,
  GetCreditTransactionsParams,
  GetKnowledgeBasesParams,
  GetKnowledgeSourcesParams,
  KnowledgeBaseListResponse,
  KnowledgeSource,
  KnowledgeSourceListResponse,
  SystemSettingListResponse,
  TaskDetail,
  TaskListResponse,
  UpdateSystemSettingRequest
} from './model';

import { useCustomInstance } from '../mutator/use-custom-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 管理端心跳
 */
export type getAdminPingResponse200 = {
  data: GetAdminPing200
  status: 200
}
    
export type getAdminPingResponseSuccess = (getAdminPingResponse200) & {
  headers: Headers;
};
;

export type getAdminPingResponse = (getAdminPingResponseSuccess)

export const getGetAdminPingUrl = () => {


  

  return `/api/v1/admin/ping`
}

export const getAdminPing = async ( options?: RequestInit): Promise<getAdminPingResponse> => {
  
  return useCustomInstance<getAdminPingResponse>(getGetAdminPingUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminPingQueryKey = () => {
    return [
    `/api/v1/admin/ping`
    ] as const;
    }

    
export const useGetAdminPingQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminPingQueryKey();

  const getAdminPing =  useGetAdminPingHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>> = ({ signal }) => getAdminPing({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminPingQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>>
export type GetAdminPingQueryError = unknown


/**
 * @summary 管理端心跳
 */

export function useGetAdminPing<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminPingHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminPingQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 数据看板统计
 */
export type getDashboardStatsResponse200 = {
  data: DashboardStats
  status: 200
}

export type getDashboardStatsResponse401 = {
  data: void
  status: 401
}

export type getDashboardStatsResponse403 = {
  data: void
  status: 403
}
    
export type getDashboardStatsResponseSuccess = (getDashboardStatsResponse200) & {
  headers: Headers;
};
export type getDashboardStatsResponseError = (getDashboardStatsResponse401 | getDashboardStatsResponse403) & {
  headers: Headers;
};

export type getDashboardStatsResponse = (getDashboardStatsResponseSuccess | getDashboardStatsResponseError)

export const getGetDashboardStatsUrl = () => {


  

  return `/api/v1/admin/dashboard/stats`
}

export const getDashboardStats = async ( options?: RequestInit): Promise<getDashboardStatsResponse> => {
  
  return useCustomInstance<getDashboardStatsResponse>(getGetDashboardStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDashboardStatsQueryKey = () => {
    return [
    `/api/v1/admin/dashboard/stats`
    ] as const;
    }

    
export const useGetDashboardStatsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();

  const getDashboardStats =  useGetDashboardStatsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>> = ({ signal }) => getDashboardStats({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardStatsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>>
export type GetDashboardStatsQueryError = void


/**
 * @summary 数据看板统计
 */

export function useGetDashboardStats<TData = Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDashboardStatsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetDashboardStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 用户列表（管理端）
 */
export type getAdminUsersResponse200 = {
  data: AdminUserListResponse
  status: 200
}
    
export type getAdminUsersResponseSuccess = (getAdminUsersResponse200) & {
  headers: Headers;
};
;

export type getAdminUsersResponse = (getAdminUsersResponseSuccess)

export const getGetAdminUsersUrl = (params?: GetAdminUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users?${stringifiedParams}` : `/api/v1/admin/users`
}

export const getAdminUsers = async (params?: GetAdminUsersParams, options?: RequestInit): Promise<getAdminUsersResponse> => {
  
  return useCustomInstance<getAdminUsersResponse>(getGetAdminUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminUsersQueryKey = (params?: GetAdminUsersParams,) => {
    return [
    `/api/v1/admin/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetAdminUsersQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>, TError = unknown>(params?: GetAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminUsersQueryKey(params);

  const getAdminUsers =  useGetAdminUsersHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>> = ({ signal }) => getAdminUsers(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminUsersQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>>
export type GetAdminUsersQueryError = unknown


/**
 * @summary 用户列表（管理端）
 */

export function useGetAdminUsers<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>, TError = unknown>(
 params?: GetAdminUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUsersHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 用户详情（管理端）
 */
export type getAdminUserByIdResponse200 = {
  data: AdminUserDetail
  status: 200
}

export type getAdminUserByIdResponse404 = {
  data: void
  status: 404
}
    
export type getAdminUserByIdResponseSuccess = (getAdminUserByIdResponse200) & {
  headers: Headers;
};
export type getAdminUserByIdResponseError = (getAdminUserByIdResponse404) & {
  headers: Headers;
};

export type getAdminUserByIdResponse = (getAdminUserByIdResponseSuccess | getAdminUserByIdResponseError)

export const getGetAdminUserByIdUrl = (userId: string,) => {


  

  return `/api/v1/admin/users/${userId}`
}

export const getAdminUserById = async (userId: string, options?: RequestInit): Promise<getAdminUserByIdResponse> => {
  
  return useCustomInstance<getAdminUserByIdResponse>(getGetAdminUserByIdUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminUserByIdQueryKey = (userId?: string,) => {
    return [
    `/api/v1/admin/users/${userId}`
    ] as const;
    }

    
export const useGetAdminUserByIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>, TError = void>(userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminUserByIdQueryKey(userId);

  const getAdminUserById =  useGetAdminUserByIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>> = ({ signal }) => getAdminUserById(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminUserByIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>>
export type GetAdminUserByIdQueryError = void


/**
 * @summary 用户详情（管理端）
 */

export function useGetAdminUserById<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>, TError = void>(
 userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminUserByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminUserByIdQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 积分账户列表
 */
export type getCreditAccountsResponse200 = {
  data: CreditAccountListResponse
  status: 200
}
    
export type getCreditAccountsResponseSuccess = (getCreditAccountsResponse200) & {
  headers: Headers;
};
;

export type getCreditAccountsResponse = (getCreditAccountsResponseSuccess)

export const getGetCreditAccountsUrl = (params?: GetCreditAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/credits/accounts?${stringifiedParams}` : `/api/v1/admin/credits/accounts`
}

export const getCreditAccounts = async (params?: GetCreditAccountsParams, options?: RequestInit): Promise<getCreditAccountsResponse> => {
  
  return useCustomInstance<getCreditAccountsResponse>(getGetCreditAccountsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCreditAccountsQueryKey = (params?: GetCreditAccountsParams,) => {
    return [
    `/api/v1/admin/credits/accounts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetCreditAccountsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>, TError = unknown>(params?: GetCreditAccountsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCreditAccountsQueryKey(params);

  const getCreditAccounts =  useGetCreditAccountsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>> = ({ signal }) => getCreditAccounts(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCreditAccountsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>>
export type GetCreditAccountsQueryError = unknown


/**
 * @summary 积分账户列表
 */

export function useGetCreditAccounts<TData = Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>, TError = unknown>(
 params?: GetCreditAccountsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditAccountsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetCreditAccountsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 积分流水列表
 */
export type getCreditTransactionsResponse200 = {
  data: CreditTransactionListResponse
  status: 200
}
    
export type getCreditTransactionsResponseSuccess = (getCreditTransactionsResponse200) & {
  headers: Headers;
};
;

export type getCreditTransactionsResponse = (getCreditTransactionsResponseSuccess)

export const getGetCreditTransactionsUrl = (params?: GetCreditTransactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/credits/transactions?${stringifiedParams}` : `/api/v1/admin/credits/transactions`
}

export const getCreditTransactions = async (params?: GetCreditTransactionsParams, options?: RequestInit): Promise<getCreditTransactionsResponse> => {
  
  return useCustomInstance<getCreditTransactionsResponse>(getGetCreditTransactionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCreditTransactionsQueryKey = (params?: GetCreditTransactionsParams,) => {
    return [
    `/api/v1/admin/credits/transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetCreditTransactionsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>, TError = unknown>(params?: GetCreditTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCreditTransactionsQueryKey(params);

  const getCreditTransactions =  useGetCreditTransactionsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>> = ({ signal }) => getCreditTransactions(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCreditTransactionsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>>
export type GetCreditTransactionsQueryError = unknown


/**
 * @summary 积分流水列表
 */

export function useGetCreditTransactions<TData = Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>, TError = unknown>(
 params?: GetCreditTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetCreditTransactionsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetCreditTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 手动调整积分
 */
export type adjustCreditResponse204 = {
  data: void
  status: 204
}
    
export type adjustCreditResponseSuccess = (adjustCreditResponse204) & {
  headers: Headers;
};
;

export type adjustCreditResponse = (adjustCreditResponseSuccess)

export const getAdjustCreditUrl = () => {


  

  return `/api/v1/admin/credits/adjust`
}

export const adjustCredit = async (adjustCreditRequest: AdjustCreditRequest, options?: RequestInit): Promise<adjustCreditResponse> => {
  
  return useCustomInstance<adjustCreditResponse>(getAdjustCreditUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adjustCreditRequest,)
  }
);}




export const useAdjustCreditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>, TError,{data: AdjustCreditRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>, TError,{data: AdjustCreditRequest}, TContext> => {

const mutationKey = ['adjustCredit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const adjustCredit =  useAdjustCreditHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>, {data: AdjustCreditRequest}> = (props) => {
          const {data} = props ?? {};

          return  adjustCredit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdjustCreditMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>>
    export type AdjustCreditMutationBody = AdjustCreditRequest
    export type AdjustCreditMutationError = unknown

    /**
 * @summary 手动调整积分
 */
export const useAdjustCredit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>, TError,{data: AdjustCreditRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useAdjustCreditHook>>>,
        TError,
        {data: AdjustCreditRequest},
        TContext
      > => {

      const mutationOptions = useAdjustCreditMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 知识库列表
 */
export type getKnowledgeBasesResponse200 = {
  data: KnowledgeBaseListResponse
  status: 200
}
    
export type getKnowledgeBasesResponseSuccess = (getKnowledgeBasesResponse200) & {
  headers: Headers;
};
;

export type getKnowledgeBasesResponse = (getKnowledgeBasesResponseSuccess)

export const getGetKnowledgeBasesUrl = (params?: GetKnowledgeBasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/knowledge-bases?${stringifiedParams}` : `/api/v1/admin/knowledge-bases`
}

export const getKnowledgeBases = async (params?: GetKnowledgeBasesParams, options?: RequestInit): Promise<getKnowledgeBasesResponse> => {
  
  return useCustomInstance<getKnowledgeBasesResponse>(getGetKnowledgeBasesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetKnowledgeBasesQueryKey = (params?: GetKnowledgeBasesParams,) => {
    return [
    `/api/v1/admin/knowledge-bases`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetKnowledgeBasesQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>, TError = unknown>(params?: GetKnowledgeBasesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKnowledgeBasesQueryKey(params);

  const getKnowledgeBases =  useGetKnowledgeBasesHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>> = ({ signal }) => getKnowledgeBases(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetKnowledgeBasesQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>>
export type GetKnowledgeBasesQueryError = unknown


/**
 * @summary 知识库列表
 */

export function useGetKnowledgeBases<TData = Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>, TError = unknown>(
 params?: GetKnowledgeBasesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeBasesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetKnowledgeBasesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 系统设置列表
 */
export type getSystemSettingsResponse200 = {
  data: SystemSettingListResponse
  status: 200
}
    
export type getSystemSettingsResponseSuccess = (getSystemSettingsResponse200) & {
  headers: Headers;
};
;

export type getSystemSettingsResponse = (getSystemSettingsResponseSuccess)

export const getGetSystemSettingsUrl = () => {


  

  return `/api/v1/admin/system/settings`
}

export const getSystemSettings = async ( options?: RequestInit): Promise<getSystemSettingsResponse> => {
  
  return useCustomInstance<getSystemSettingsResponse>(getGetSystemSettingsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSystemSettingsQueryKey = () => {
    return [
    `/api/v1/admin/system/settings`
    ] as const;
    }

    
export const useGetSystemSettingsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemSettingsQueryKey();

  const getSystemSettings =  useGetSystemSettingsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>> = ({ signal }) => getSystemSettings({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSystemSettingsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>>
export type GetSystemSettingsQueryError = unknown


/**
 * @summary 系统设置列表
 */

export function useGetSystemSettings<TData = Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetSystemSettingsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetSystemSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 更新系统设置
 */
export type updateSystemSettingResponse204 = {
  data: void
  status: 204
}
    
export type updateSystemSettingResponseSuccess = (updateSystemSettingResponse204) & {
  headers: Headers;
};
;

export type updateSystemSettingResponse = (updateSystemSettingResponseSuccess)

export const getUpdateSystemSettingUrl = () => {


  

  return `/api/v1/admin/system/settings`
}

export const updateSystemSetting = async (updateSystemSettingRequest: UpdateSystemSettingRequest, options?: RequestInit): Promise<updateSystemSettingResponse> => {
  
  return useCustomInstance<updateSystemSettingResponse>(getUpdateSystemSettingUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSystemSettingRequest,)
  }
);}




export const useUpdateSystemSettingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>, TError,{data: UpdateSystemSettingRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>, TError,{data: UpdateSystemSettingRequest}, TContext> => {

const mutationKey = ['updateSystemSetting'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const updateSystemSetting =  useUpdateSystemSettingHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>, {data: UpdateSystemSettingRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateSystemSetting(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSystemSettingMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>>
    export type UpdateSystemSettingMutationBody = UpdateSystemSettingRequest
    export type UpdateSystemSettingMutationError = unknown

    /**
 * @summary 更新系统设置
 */
export const useUpdateSystemSetting = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>, TError,{data: UpdateSystemSettingRequest}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdateSystemSettingHook>>>,
        TError,
        {data: UpdateSystemSettingRequest},
        TContext
      > => {

      const mutationOptions = useUpdateSystemSettingMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 操作日志
 */
export type getAuditLogsResponse200 = {
  data: AuditLogListResponse
  status: 200
}
    
export type getAuditLogsResponseSuccess = (getAuditLogsResponse200) & {
  headers: Headers;
};
;

export type getAuditLogsResponse = (getAuditLogsResponseSuccess)

export const getGetAuditLogsUrl = (params?: GetAuditLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/audit-logs?${stringifiedParams}` : `/api/v1/admin/audit-logs`
}

export const getAuditLogs = async (params?: GetAuditLogsParams, options?: RequestInit): Promise<getAuditLogsResponse> => {
  
  return useCustomInstance<getAuditLogsResponse>(getGetAuditLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAuditLogsQueryKey = (params?: GetAuditLogsParams,) => {
    return [
    `/api/v1/admin/audit-logs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetAuditLogsQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>, TError = unknown>(params?: GetAuditLogsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuditLogsQueryKey(params);

  const getAuditLogs =  useGetAuditLogsHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>> = ({ signal }) => getAuditLogs(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuditLogsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>>
export type GetAuditLogsQueryError = unknown


/**
 * @summary 操作日志
 */

export function useGetAuditLogs<TData = Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>, TError = unknown>(
 params?: GetAuditLogsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAuditLogsHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAuditLogsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 全平台任务列表
 */
export type getAdminTasksResponse200 = {
  data: TaskListResponse
  status: 200
}
    
export type getAdminTasksResponseSuccess = (getAdminTasksResponse200) & {
  headers: Headers;
};
;

export type getAdminTasksResponse = (getAdminTasksResponseSuccess)

export const getGetAdminTasksUrl = (params?: GetAdminTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/tasks?${stringifiedParams}` : `/api/v1/admin/tasks`
}

export const getAdminTasks = async (params?: GetAdminTasksParams, options?: RequestInit): Promise<getAdminTasksResponse> => {
  
  return useCustomInstance<getAdminTasksResponse>(getGetAdminTasksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminTasksQueryKey = (params?: GetAdminTasksParams,) => {
    return [
    `/api/v1/admin/tasks`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetAdminTasksQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>, TError = unknown>(params?: GetAdminTasksParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTasksQueryKey(params);

  const getAdminTasks =  useGetAdminTasksHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>> = ({ signal }) => getAdminTasks(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminTasksQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>>
export type GetAdminTasksQueryError = unknown


/**
 * @summary 全平台任务列表
 */

export function useGetAdminTasks<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>, TError = unknown>(
 params?: GetAdminTasksParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTasksHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminTasksQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 任务详情（管理端）
 */
export type getAdminTaskByIdResponse200 = {
  data: TaskDetail
  status: 200
}
    
export type getAdminTaskByIdResponseSuccess = (getAdminTaskByIdResponse200) & {
  headers: Headers;
};
;

export type getAdminTaskByIdResponse = (getAdminTaskByIdResponseSuccess)

export const getGetAdminTaskByIdUrl = (taskId: string,) => {


  

  return `/api/v1/admin/tasks/${taskId}`
}

export const getAdminTaskById = async (taskId: string, options?: RequestInit): Promise<getAdminTaskByIdResponse> => {
  
  return useCustomInstance<getAdminTaskByIdResponse>(getGetAdminTaskByIdUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminTaskByIdQueryKey = (taskId?: string,) => {
    return [
    `/api/v1/admin/tasks/${taskId}`
    ] as const;
    }

    
export const useGetAdminTaskByIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>, TError = unknown>(taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTaskByIdQueryKey(taskId);

  const getAdminTaskById =  useGetAdminTaskByIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>> = ({ signal }) => getAdminTaskById(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminTaskByIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>>
export type GetAdminTaskByIdQueryError = unknown


/**
 * @summary 任务详情（管理端）
 */

export function useGetAdminTaskById<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>, TError = unknown>(
 taskId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminTaskByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminTaskByIdQueryOptions(taskId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 订单列表
 */
export type getAdminOrdersResponse200 = {
  data: AdminOrderListResponse
  status: 200
}
    
export type getAdminOrdersResponseSuccess = (getAdminOrdersResponse200) & {
  headers: Headers;
};
;

export type getAdminOrdersResponse = (getAdminOrdersResponseSuccess)

export const getGetAdminOrdersUrl = (params?: GetAdminOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/orders?${stringifiedParams}` : `/api/v1/admin/orders`
}

export const getAdminOrders = async (params?: GetAdminOrdersParams, options?: RequestInit): Promise<getAdminOrdersResponse> => {
  
  return useCustomInstance<getAdminOrdersResponse>(getGetAdminOrdersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminOrdersQueryKey = (params?: GetAdminOrdersParams,) => {
    return [
    `/api/v1/admin/orders`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetAdminOrdersQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>, TError = unknown>(params?: GetAdminOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminOrdersQueryKey(params);

  const getAdminOrders =  useGetAdminOrdersHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>> = ({ signal }) => getAdminOrders(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminOrdersQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>>
export type GetAdminOrdersQueryError = unknown


/**
 * @summary 订单列表
 */

export function useGetAdminOrders<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>, TError = unknown>(
 params?: GetAdminOrdersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrdersHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 订单详情
 */
export type getAdminOrderByIdResponse200 = {
  data: AdminOrder
  status: 200
}
    
export type getAdminOrderByIdResponseSuccess = (getAdminOrderByIdResponse200) & {
  headers: Headers;
};
;

export type getAdminOrderByIdResponse = (getAdminOrderByIdResponseSuccess)

export const getGetAdminOrderByIdUrl = (orderId: string,) => {


  

  return `/api/v1/admin/orders/${orderId}`
}

export const getAdminOrderById = async (orderId: string, options?: RequestInit): Promise<getAdminOrderByIdResponse> => {
  
  return useCustomInstance<getAdminOrderByIdResponse>(getGetAdminOrderByIdUrl(orderId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAdminOrderByIdQueryKey = (orderId?: string,) => {
    return [
    `/api/v1/admin/orders/${orderId}`
    ] as const;
    }

    
export const useGetAdminOrderByIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>, TError = unknown>(orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminOrderByIdQueryKey(orderId);

  const getAdminOrderById =  useGetAdminOrderByIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>> = ({ signal }) => getAdminOrderById(orderId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminOrderByIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>>
export type GetAdminOrderByIdQueryError = unknown


/**
 * @summary 订单详情
 */

export function useGetAdminOrderById<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>, TError = unknown>(
 orderId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminOrderByIdHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetAdminOrderByIdQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 退款
 */
export type refundOrderResponse204 = {
  data: void
  status: 204
}
    
export type refundOrderResponseSuccess = (refundOrderResponse204) & {
  headers: Headers;
};
;

export type refundOrderResponse = (refundOrderResponseSuccess)

export const getRefundOrderUrl = (orderId: string,) => {


  

  return `/api/v1/admin/orders/${orderId}/refund`
}

export const refundOrder = async (orderId: string, options?: RequestInit): Promise<refundOrderResponse> => {
  
  return useCustomInstance<refundOrderResponse>(getRefundOrderUrl(orderId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const useRefundOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>, TError,{orderId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>, TError,{orderId: string}, TContext> => {

const mutationKey = ['refundOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const refundOrder =  useRefundOrderHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>, {orderId: string}> = (props) => {
          const {orderId} = props ?? {};

          return  refundOrder(orderId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefundOrderMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>>
    
    export type RefundOrderMutationError = unknown

    /**
 * @summary 退款
 */
export const useRefundOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>, TError,{orderId: string}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRefundOrderHook>>>,
        TError,
        {orderId: string},
        TContext
      > => {

      const mutationOptions = useRefundOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 知识源列表
 */
export type getKnowledgeSourcesResponse200 = {
  data: KnowledgeSourceListResponse
  status: 200
}
    
export type getKnowledgeSourcesResponseSuccess = (getKnowledgeSourcesResponse200) & {
  headers: Headers;
};
;

export type getKnowledgeSourcesResponse = (getKnowledgeSourcesResponseSuccess)

export const getGetKnowledgeSourcesUrl = (params?: GetKnowledgeSourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/knowledge/sources?${stringifiedParams}` : `/api/v1/admin/knowledge/sources`
}

export const getKnowledgeSources = async (params?: GetKnowledgeSourcesParams, options?: RequestInit): Promise<getKnowledgeSourcesResponse> => {
  
  return useCustomInstance<getKnowledgeSourcesResponse>(getGetKnowledgeSourcesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetKnowledgeSourcesQueryKey = (params?: GetKnowledgeSourcesParams,) => {
    return [
    `/api/v1/admin/knowledge/sources`, ...(params ? [params]: [])
    ] as const;
    }

    
export const useGetKnowledgeSourcesQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>, TError = unknown>(params?: GetKnowledgeSourcesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKnowledgeSourcesQueryKey(params);

  const getKnowledgeSources =  useGetKnowledgeSourcesHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>> = ({ signal }) => getKnowledgeSources(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>, TError, TData> & { queryKey: QueryKey }
}

export type GetKnowledgeSourcesQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>>
export type GetKnowledgeSourcesQueryError = unknown


/**
 * @summary 知识源列表
 */

export function useGetKnowledgeSources<TData = Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>, TError = unknown>(
 params?: GetKnowledgeSourcesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetKnowledgeSourcesHook>>>, TError, TData>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = useGetKnowledgeSourcesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary 创建或上传知识源
 */
export type createKnowledgeSourceResponse201 = {
  data: KnowledgeSource
  status: 201
}
    
export type createKnowledgeSourceResponseSuccess = (createKnowledgeSourceResponse201) & {
  headers: Headers;
};
;

export type createKnowledgeSourceResponse = (createKnowledgeSourceResponseSuccess)

export const getCreateKnowledgeSourceUrl = () => {


  

  return `/api/v1/admin/knowledge/sources`
}

export const createKnowledgeSource = async (knowledgeSource: KnowledgeSource, options?: RequestInit): Promise<createKnowledgeSourceResponse> => {
  
  return useCustomInstance<createKnowledgeSourceResponse>(getCreateKnowledgeSourceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      knowledgeSource,)
  }
);}




export const useCreateKnowledgeSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>, TError,{data: KnowledgeSource}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>, TError,{data: KnowledgeSource}, TContext> => {

const mutationKey = ['createKnowledgeSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      const createKnowledgeSource =  useCreateKnowledgeSourceHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>, {data: KnowledgeSource}> = (props) => {
          const {data} = props ?? {};

          return  createKnowledgeSource(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateKnowledgeSourceMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>>
    export type CreateKnowledgeSourceMutationBody = KnowledgeSource
    export type CreateKnowledgeSourceMutationError = unknown

    /**
 * @summary 创建或上传知识源
 */
export const useCreateKnowledgeSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>, TError,{data: KnowledgeSource}, TContext>, request?: SecondParameter<ReturnType<typeof useCustomInstance>>}
 ): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateKnowledgeSourceHook>>>,
        TError,
        {data: KnowledgeSource},
        TContext
      > => {

      const mutationOptions = useCreateKnowledgeSourceMutationOptions(options);

      return useMutation(mutationOptions);
    }
