/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Medagil API
 * Medagil 医学科研写作平台 API 规范（MVP 阶段）。 - 用户端与管理端 REST API，路径与 tag 区分 - 内部接口（internal tag）用于 api-service 与 ai-service / 其它服务间调用

 * OpenAPI spec version: 0.2.0
 */

export type UserProfilePlan = typeof UserProfilePlan[keyof typeof UserProfilePlan];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfilePlan = {
  free: 'free',
  pro: 'pro',
  max: 'max',
} as const;
